### ISSUE TITLE
Создать механизм проверки данных в appsettigs с последующим шифррованием

### ISSUE THREAD

**Issue by Kvarkas** [Kvarkas/team.holiday#15]
1)Добавить отдельный класс в проект, который будет отвечать за шифрование и дешифрование данных.
2)Применить созданый класс для проверки и шифрования данных в appsettings.
Должно проверять, имеются ли зашифрованные данные, если нет, шифровать их.

* Сделать отдельную утилиту, бази́рующуюся на данном классе, которая сможет запускаться после билда и шифровать данные не дожидаясь первого запуска проекта

**Comment by Kvarkas** [comment]
Частичная зависимость от https://github.com/MyTeam-Holiday/server-side/issues/14

**Comment by ValeraBro** [comment]
ой бл, ну ладно, сейчас тогда закину всё. Ля,мискликнул

**Comment by ValeraBro** [comment]
<details><summary>Details :)</summary>
<p>
ща все будет скоро, донт ворри


</p>
</details>

**Comment by ValeraBro** [comment]
![5yE](https://github.com/MyTeam-Holiday/server-side/assets/138037567/292c53d1-d5f9-40f2-93db-57ebf1715b36)
